### ISSUE TITLE
Deleting multiple records in Entity Browser is not possible

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#184]
After selecting multiple records, deleting all of them at once is not possible in Entity Browser.

**Comment by wondie** [comment]
I pulled the latest commits and now I get the following error. 

```
An error has occurred while executing Python code: 

IndexError: list assignment index out of range 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\entity_browser.py", line 895, in onRemoveEntity
    self._deleteRecord(rec_ids, row_numbers)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\ui\entity_browser.py", line 952, in _deleteRecord
    self._tableModel.removeRows(row_numbers[i], 1)
  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\stdm\data\qtmodels.py", line 525, in removeRows
    del self._initData[position]
IndexError: list assignment index out of range


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

Python Path:
C:/Users/Wondim/.qgis2/python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/Wondim/.qgis2/python
C:/Users/Wondim/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Wondim/.qgis2//python
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm\third_party\fontTools
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm_ref_config\third_party
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\stdm_ref_config\third_party\fontTools
```

**Comment by gkahiu** [comment]
This error was brought about by a WIP (Work In Progress) commit, it is fixed now.

**Comment by wondie** [comment]
I just checked that it is working well now!

**Comment by wondie** [comment]
I just discovered that, even though it removes it from the entity browser, when I restart the entity browser, the deleted rows show up again and the still exist in the database table too.

**Comment by gkahiu** [comment]
I thought it was fixed but indeed it was NOT because I did not test it in a situation where the record (to be deleted) is referenced in another table. In my case, the party record was participating in a social tenure relationship and as such, the entity browser was flagging it as having been removed but it was not. 

In this case, there was an integrity error being raised by the DB but [this](https://github.com/gltn/stdm/blob/rel-1_4_0/data/database.py#L259) code was suppressing the error. As a result, the calling model was not 'aware' of this exception and the command was assumed to be successful.

I have fixed it by capturing the result and notifying the user to check if the record participates in an STR or is referenced by a related entity. I have pushed this to **rel-1_4_1** and **master** branches respectively.

Please test and confirm.

**Comment by wondie** [comment]
I have confirmed that this issue is fixed.
