### ISSUE TITLE
Spatial Unit Manager Icon Check State

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#24]
The check states for QAction associated with the showing/hiding the Spatial Unit Manager dockable window have been mixed up. Currently, when the Spatial Unit Manager window is visible, the icon is unchecked whereas when the window is closed then the icon appears checked. I believe this behavior should be the inverted.

**Comment by eomwandho** [comment]
The issue has been fixed.

**Comment by gkahiu** [comment]
Have you updated the repository because am still experiencing the same issue

**Comment by eomwandho** [comment]
This issue has been fixed and uploaded to repo
