### ISSUE TITLE
Error when Column proprty clicked on the Column Editor window

### ISSUE THREAD

**Issue by geonomad-consulting** [gltn/stdm#67]
The error below is thrown when column editor is clicked

`Traceback (most recent call last):
  File "~/.qgis2/python/plugins/stdm/ui/wizard/column_editor.py", line 272, in data_type_property
    self.type_attribs[self.current_type_info()]['property']()
  File "~/.qgis2/python/plugins/stdm/ui/wizard/column_editor.py", line 332, in geometry_property
    editor = GeometryProperty(self, self.form_fields)
  File "~/.qgis2/python/plugins/stdm/ui/wizard/geometry_property.py", line 55, in __init__
    self.init_gui()
  File "~/.qgis2/python/plugins/stdm/ui/wizard/geometry_property.py", line 70, in init_gui
    self.btnCoord.setText(self.srid())
TypeError: QAbstractButton.setText(QString): argument 1 has unexpected type 'int'`

![column editor error](https://cloud.githubusercontent.com/assets/17067856/15447845/fe094ffe-1f57-11e6-90f4-97f512419299.png)

The error above

**Comment by pgathogo** [comment]
Fixed, correct type "str" now passed to method setText().

**Comment by geonomad-consulting** [comment]
Still throwing the error. Even though I have updated my fork

Traceback (most recent call last):
  File "~/.qgis2/python/plugins/stdm/ui/wizard/column_editor.py", line 273, in data_type_property
    self.type_attribs[self.current_type_info()]['property']()
  File "~/.qgis2/python/plugins/stdm/ui/wizard/column_editor.py", line 333, in geometry_property
    editor = GeometryProperty(self, self.form_fields)
  File "~/.qgis2/python/plugins/stdm/ui/wizard/geometry_property.py", line 55, in __init__
    self.init_gui()
  File "~/.qgis2/python/plugins/stdm/ui/wizard/geometry_property.py", line 70, in init_gui
    self.btnCoord.setText(self.srid())
TypeError: QAbstractButton.setText(QString): argument 1 has unexpected type 'int'

**Comment by gkahiu** [comment]
Was this fixed?

**Comment by pgathogo** [comment]
yes, this is fixed.
